services:
  router-db-dev:
    image: postgres:16-alpine
    container_name: router-db-dev
    restart: unless-stopped
    networks:
      - orion-network
    environment:
      POSTGRES_DB: orion_router_dev
      POSTGRES_USER: router_user_dev
      POSTGRES_PASSWORD: router_pass_dev
    ports:
      - "5444:5432" # Dev port is 5444 (Prod uses 5433 or 5432)
    volumes:
      - router_postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U router_user_dev -d orion_router_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  router_postgres_dev_data: # Completely isolated volume for Dev db

networks:
  orion-network:
    name: orion-network
    external: true

